module.exports = {
    GOOGLE_BOT_HEADERS: {
        'User-Agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
        'Referer': 'https://www.google.com/',
        'X-Forwarded-For': '66.249.66.1',
    },
    MAX_DATASET_ITEMS_LOADED: 3 * 1000 * 1000,
    ARTICLES_SCRAPED_DATASET_PREFIX: 'ARTICLES-SCRAPED-',
    POSSIBLE_SITEMAP_PATHS: [
        '/sitemap.xml',
        '/product_index.xml',
        '/product_template.xml',
        '/sitemap_index.xml',
        '/sitemaps/sitemap_index.xml',
        '/sitemap/product_index.xml',
        '/media/sitemap.xml',
        '/media/sitemap/sitemap.xml',
        '/media/sitemap/index.xml',
        '/sitemap',
        '/category-sitemap',
        '/sitemap.html',
        '/sitemap_index',
        '/sitemap.xml.gz',
        '/product_index.xml.gz',
        '/product_template.xml.gz',
        '/sitemap_index.xml.gz',
        '/sitemaps/sitemap_index.xml.gz',
        '/sitemap/product_index.xml.gz',
        '/media/sitemap.xml.gz',
        '/media/sitemap/sitemap.xml.gz',
        '/media/sitemap/index.xml.gz',
        '/sitemap.xml.tar.gz',
        '/product_index.xml.tar.gz',
        '/product_template.xml.tar.gz',
        '/sitemap_index.xml.tar.gz',
        '/sitemaps/sitemap_index.xml.tar.gz',
        '/sitemap/product_index.xml.tar.gz',
        '/media/sitemap.xml.tar.gz',
        '/media/sitemap/sitemap.xml.tar.gz',
        '/media/sitemap/index.xml.tar.gz',
        '/robots.txt',
        '/_sitemap-categories.xml',
    ]
};
